# Generated by Django 4.0.4 on 2022-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
